name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7.7
        architecture: x64
      env:
        AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    - name: Test with Pytest
      working-directory: ./JupyterServerExtension
      run: pytest tests
    - name: Build the Docker image
      working-directory: ./JupyterServerExtension
      run: docker build . --file Dockerfile --tag jupyter-server:$(date +%s)
